Metrics/AbcSize:
  Max: 18

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 110
  AllowURI: true

Style/SymbolArray:
  MinSize: 3

Metrics/MethodLength:
  Max: 15

Naming/UncommunicativeMethodParamName:
  MinNameLength: 1
  AllowNamesEndingInNumbers: false

# Near-duplicate of a file from an external package, want to keep changes minimal
AllCops:
  Exclude:
    - 'lib/extensions/httparty/hash_conversions.rb'
